"""
Body measurements module — loads body profile and wraps 2D panel points onto body.

Reads from the validated body profile JSON (generated by analyze_body.py).
Provides interpolated cross-section data at arbitrary Y-heights and
a wrap function that maps 2D panel coordinates onto the body's elliptical
cross-section.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np


@dataclass
class BodySlice:
    """Measurements at a single Y-height."""
    y: float
    width: float
    depth: float
    circumference: float
    center_x: float
    center_z: float
    x_left: float
    x_right: float
    z_front: float
    z_back: float


@dataclass
class BodyProfile:
    """Complete body profile loaded from JSON."""
    slices: list[BodySlice]
    landmarks: dict
    bounds: dict

    # Cached arrays for fast interpolation
    _ys: np.ndarray = None
    _widths: np.ndarray = None

    def __post_init__(self):
        self._ys = np.array([s.y for s in self.slices])

    @property
    def shoulder_y(self): return self.landmarks.get("shoulder_y", 1.43)
    @property
    def armpit_y(self): return self.landmarks.get("armpit_y", 1.23)
    @property
    def chest_y(self): return self.landmarks.get("chest_y", 1.29)
    @property
    def waist_y(self): return self.landmarks.get("waist_y", 1.03)
    @property
    def hip_y(self): return self.landmarks.get("hip_y", 0.80)
    @property
    def neck_y(self): return self.landmarks.get("neck_y", 1.52)
    @property
    def chest_circumference(self): return self.landmarks.get("chest_circumference", 1.02)

    def at_y(self, y: float) -> BodySlice:
        """Interpolate body measurements at arbitrary Y height."""
        idx = np.clip(np.searchsorted(self._ys, y) - 1, 0, len(self._ys) - 2)
        s0 = self.slices[idx]
        s1 = self.slices[idx + 1]

        if abs(s1.y - s0.y) < 1e-6:
            return s0

        t = np.clip((y - s0.y) / (s1.y - s0.y), 0.0, 1.0)

        def lerp(a, b):
            return a + t * (b - a)

        return BodySlice(
            y=y,
            width=lerp(s0.width, s1.width),
            depth=lerp(s0.depth, s1.depth),
            circumference=lerp(s0.circumference, s1.circumference),
            center_x=lerp(s0.center_x, s1.center_x),
            center_z=lerp(s0.center_z, s1.center_z),
            x_left=lerp(s0.x_left, s1.x_left),
            x_right=lerp(s0.x_right, s1.x_right),
            z_front=lerp(s0.z_front, s1.z_front),
            z_back=lerp(s0.z_back, s1.z_back),
        )


def load_profile(profile_path: str = "data/bodies/mannequin_profile.json") -> BodyProfile:
    """Load body profile from JSON."""
    with open(profile_path) as f:
        data = json.load(f)

    slices = []
    for s in data["cross_sections"]:
        t = s["torso"]
        slices.append(BodySlice(
            y=s["y"],
            width=t["width"],
            depth=t["depth"],
            circumference=t["circumference"],
            center_x=t["center_x"],
            center_z=t["center_z"],
            x_left=t["x_left"],
            x_right=t["x_right"],
            z_front=t["z_front"],
            z_back=t["z_back"],
        ))

    return BodyProfile(
        slices=slices,
        landmarks=data["landmarks"],
        bounds=data["bounds"],
    )


def wrap_point(
    profile: BodyProfile,
    local_x: float,
    local_y: float,
    panel_width: float,
    side: str = "front",
    offset: float = 0.015,
) -> tuple[float, float, float]:
    """
    Map a 2D panel point (local_x, local_y) onto the body surface.

    local_x: horizontal position on panel [0, panel_width]
    local_y: vertical position (maps directly to world Y height)
    panel_width: total panel width in meters
    side: "front" or "back"
    offset: clearance from body surface (meters)

    The cross-section at each height is approximated as an ellipse.
    For FRONT panel: angle sweeps from left side (-π/2) through front center (0) to right side (+π/2)
    For BACK  panel: angle sweeps from right side (+π/2) through back center (π) to left side (+3π/2)
    """
    body = profile.at_y(local_y)

    # Ellipse semi-axes with clearance
    a = body.width / 2 + offset   # X half-axis
    b = body.depth / 2 + offset   # Z half-axis

    # Map local_x to normalized position [-0.5, 0.5]
    t = (local_x / panel_width) - 0.5

    if side == "front":
        theta = t * np.pi  # [-π/2, +π/2]
    else:
        theta = np.pi + t * np.pi  # [+π/2, +3π/2]

    world_x = body.center_x + a * np.sin(theta)
    world_z = body.center_z + b * np.cos(theta)
    world_y = local_y

    return (float(world_x), float(world_y), float(world_z))
